### ISSUE TITLE
Robotjs not installing correctly

### ISSUE THREAD

**Issue by csf30816** [Mega-Mewthree/Moomoo-AI-Bot-Sender#25]
```cmd
//Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master>npm config set python python2.7

C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master>npm config set msvs_version 2015

C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master>npm install robotjs

> robotjs@0.4.7 install C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master\node_modules\robotjs
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\robotjs-v0.4.7-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\*user*\AppData\Roaming\npm-cache\_prebuilds\https-github.com-octalmage-robotjs-releases-download-v0.4.7-robotjs-v0.4.7-
node-v59-win32-x64.tar.gz
prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v59-win32-x64.tar.gz
prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.4.7/robotjs-v0.4.7-node-v59-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.0.0 runtime=node arch=x64 platform=win32)

C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Users\*user*\AppData\Roaming\n
pm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\*user*\AppData\Roaming\npm\node_modules\np
m\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master\node_modules\robotjs\build\robotjs.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Def
ault.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\*user*\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\*user*\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master\node_modules\robotjs
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\*user*\AppData\Roaming\npm-cache\_logs\2018-04-01T04_03_31_743Z-debug.log

C:\Users\*user*\Moomoo-AI-Bot-Sender-master\Moomoo-AI-Bot-Sender-master>
```

I don't know what went wrong

**Comment by Sam1370** [comment]
FIX THE PROBLEM BY INSTALLING THIS:
[visualcppbuildtools_full.zip](https://github.com/Mega-Mewthree/Moomoo-AI-Bot-Sender/files/1959058/visualcppbuildtools_full.zip)
